config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  resources :pictures do
  end
  devise_for :users
  root 'products#index'

  resources :products do
    collection do
      get '/products/search'
    end

  end
  
  resources :cart_items do
    member do 
      post :increment
      post :decrement
    end
  end
  resources :order_items do
  end
 resources :orders do
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :products, through: :cart_items
	has_many :cart_items

	belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  has_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items

	belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  # belongs_to :cart_item
  belongs_to :order,:dependent => :destroy
end

app/models/picture.rb
class Picture < ApplicationRecord
	  has_one_attached :image 

	 belongs_to :imageable, polymorphic: true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :cart_items
	# has_many :carts
	has_many :order_items

	has_one :picture, as: :imageable

	def name
    productName
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable\

  has_one :cart
  has_many :orders
  has_one :picture, as: :imageable

  

end

app/controllers/carts_controller.rb
	class CartsController < ApplicationController
	def show
		
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def show
		@order = Order.find(params[:id])
		@order_items = @order.order_items
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	# def index
 #    @users = User.all
 #  end
  def new
    @picture = Picture.new
  end

  def create
    @user = current_user
    current_user.picture.destroy if current_user.picture.present?
 
    @picture = Picture.create!(image: params[:picture][:image], imageable: current_user)
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/product_pictures/_form.html.erb
<%= semantic_form_for [:admin, @product_picture], url: admin_product_pictures_path, builder: ActiveAdmin::FormBuilder do |f| %>

    <%= f.inputs do %>
      <%= f.input :imageable_id, :label => "Product", as: :select, :collection => Product.all %>
      
      <%= f.input :imageable_type, as: :hidden, :input_html => { :value => "Product"} %>
      <%= f.input :image, as: :file %>
      <%= f.actions %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <style>
      .top{
        position: relative;
        text-align: center;
        border-width: 20px;
        margin-left: 0px;
        margin-right: 0px;
        padding-top: 15px;
        padding-bottom: 15px;
        background-color: blue;
      }
      #search{
        width: 348px;
      }
      a{
        color: blue;
        width: auto;
        background-color: white;
        margin: 3px;
        padding-top:5px;
        padding-bottom:5px;
        padding-left:7px;
        padding-right:7px;
        text-decoration: none;


      }
      a:hover{
        text-decoration: none;
      }
      .home{
        padding-top: 20px;
        padding-left: 10px;
        
      }
    </style>
  </head>
  <body>
    <div class="top">
    <div class="row text-center">
      <div class="col-1">
        <%= link_to "home", products_path %>  
      </div>
      <div class="col-5">
        <center>
          <%= form_with url: products_search_products_path, method: :get do |form| %>
          <%= form.text_field :search ,placeholder: 'search for produts,brands and mode' %>
          <%= form.submit "Search" %>
          <% end %>
        </center>
      </div>
      <div class="col-6">
        <div class="row">
          <div class="col-6">
            <div class="row">
              <% if user_signed_in? %>
              <div class="col-8  link" style="text-decoration: none;">
                 <% if current_user.picture == nil %>
                    <%= link_to current_user.email,edit_user_registration_path %>
                 <% else %>
                   <%= link_to  edit_user_registration_path do %>
                  <%= image_tag current_user.picture.image.variant(resize_to_limit: [20, 20]) %>
                  <% end %>
                <% end %>
                <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete}%>
              </div>
              <% else %>
              <div class="col-4 link" style=" text-decoration: none;">  
                <%= link_to "Log in", new_user_session_path %>  
              </div>
              <% end %>  
            </div>
          </div>
          <div class="col-6">
            <div class="row">
              <div class="col-3 link" >
                <%= link_to "Cart", cart_items_path%> 
              </div>
              <div class="col-3 link" style=" text-decoration: none;">
                <%= link_to "Orders", order_items_path%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
    <div class="home">
      <%= yield %>
    </div>
  </body>
</html>