config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  resources :pictures do
  end
  devise_for :users
  root 'products#index'

  resources :products do
    collection do
      get '/products/search'
    end

  end
  
  resources :cart_items do
    member do 
      post :increment
      post :decrement
    end
  end
  resources :order_items do
  end
 resources :orders do
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :products, through: :cart_items
	has_many :cart_items

	belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  has_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items

	belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  # belongs_to :cart_item
  belongs_to :order,:dependent => :destroy
end

app/models/picture.rb
class Picture < ApplicationRecord
	  has_one_attached :image 

	 belongs_to :imageable, polymorphic: true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :cart_items
	# has_many :carts
	has_many :order_items

	has_one :picture, as: :imageable

	def name
    productName
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable\

  has_one :cart
  has_many :orders
  has_one :picture, as: :imageable

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

	def index
		if current_user == nil
			redirect_to new_user_session_path
		else
			@user = current_user
			@cart= @user.cart || @user.create_cart
			@cart_items = @cart.cart_items
		end
		
	end
	def create
		if current_user == nil
			redirect_to new_user_session_path
		else
		@user = current_user

		@product = Product.find(params[:product_id])

		@cart= @user.cart

		@cart_item = @cart.cart_items.create(:product_id => @product.id)
		redirect_to products_path
		end
		
	end
	def destroy
		# binding.break

		@user = current_user
		@cart = @user.cart 
		@cart_item = @cart.cart_items.find(params[:id])
		@cart_item.destroy

		redirect_to cart_items_path
	end

	def increment
		@cart_item = CartItem.find(params[:id])
		@cart_item.increment!(:quantity)
		redirect_to cart_items_path
	end
	def decrement
		@cart_item = CartItem.find(params[:id])
		if @cart_item.quantity <=1
			redirect_to cart_items_path
		else
		@cart_item.decrement!(:quantity)
		redirect_to cart_items_path
		end
	end
end

app/controllers/carts_controller.rb
	class CartsController < ApplicationController
	def show
		
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def show
		@order = Order.find(params[:id])
		@order_items = @order.order_items
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	# def index
 #    @users = User.all
 #  end
  def new
    @picture = Picture.new
  end

  def create
    @user = current_user
    current_user.picture.destroy if current_user.picture.present?
 
    @picture = Picture.create!(image: params[:picture][:image], imageable: current_user)
    redirect_to root_path
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    # binding.break
    Product.paginates_per 5
    page_number = params[:page] || 1 

    if params[:orderby] == "1" 
       @products = Product.order(productPrice: :desc).page(page_number)
    elsif params[:orderby]== "0"
       @products = Product.order(productPrice: :asc).page(page_number)
    else
       @products = Product.order(:productName).page(page_number)
    end         

    # @products = Product.order(productPrice: :params[:price]).page(page_number)

  end
 
  def search
    # binding.break 
    Product.paginates_per 3
    page_number = params[:page] || 1 
    @products = Product.where("productName LIKE ?", "%#{params[:search]}%").page(page_number)
    
    render 'index'
    # redirect_to products_path(@products)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart_items/index.html.erb
<h2>cart</h2>


<div>
	<div class="row" style="margin-left: 20px;">
			<div class="col-8">
				<% @cart_items.each do |cart_item| %>
				<div class="row">
					<div class="col-3" style="padding: 10px;">
						<p><%= image_tag cart_item.product.picture.image.variant(resize_to_limit: [150,150]) %></p>
						<div class="row">
							<div class="col-4">
								<%= link_to "-", decrement_cart_item_path(cart_item.id), :class => "button",data: { "turbo-method": :post }  %>
									
							</div>
							<div class="col-2">
								<p><%= cart_item.quantity %></p>
							</div>
							<div class="col-4">
								<%= link_to "+", increment_cart_item_path(cart_item.id), :class => "button",data: { "turbo-method": :post }  %>
							</div>
						</div>
					</div>
					<div class="col-7">
						<h5><%= cart_item.product.productName %></h5>
						<p>Rs.<%= cart_item.product.productPrice.to_s(:delimited) %></p>
						<p ><%= link_to "Remove from cart", cart_item_path(id:cart_item.id), :confirm => 'Are you sure?', :class => "button",data: { "turbo-method": :delete }  %></p>
					</div>
				</div>
				<b><hr></b>
				<% end %>
			</div>
		</div>
	</div>

<div style="margin-bottom: 20px;">
	<% if @cart_items !=[] %>
  <%= link_to "place Order", 'http://localhost:3000/order_items',  data: { "turbo-method": :post }  %>
  <% end %>
  
	
</div>
	

	

app/views/orders/show.html.erb
	<div class="row">
		<% @order_items.each do |order_item| %>
	  <div class="col-12" style="margin-top: 15px;">
          <div class="row" >
            <div class="col-3" style="padding: 10px;">
              <% if order_item.product.picture == nil %>
              <% else %>
              <div style="text-align: center;">
                <%= image_tag order_item.product.picture.image.variant(resize_to_limit: [200,200]) %>
              </div>
                
              <% end %>
            </div>
            <div class="col-6">
              <h5><%= order_item.product.productName %></h5>
              <ul>
                <li><%= order_item.product.memory %></li>
                <li><%= order_item.product.displaySize %></li>
                <li><%= order_item.product.camaras %></li>
                <li><%= order_item.product.battery %></li>
                <li><%= order_item.product.processor %></li>
              </ul>
            </div>
            <div class="col-3"> 
            	<p> <b>price (for<%= order_item.quantity.to_s(:delimited) %> pices):Rs.<%= order_item.totalPrice.to_s(:delimited) %> </b></p>
            </div>
          </div>
        </div>
		<% end %>
	</div>
	 
</div>
<%= link_to "back", order_items_path%>


		

app/views/pictures/new.html.erb
<%= form_with model: @picture do |form| %>
  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>

  </div>

  <div>
    <%= form.submit %>
  </div>
  <% end %>

app/views/products/index.html.erb
<div>
  <div class="row">
    <div class="col-3">
      <form name="form1" method="get" action="/products">
      <p>
        <label for="price">sort by price:</label>
        <select id="price" name="orderby" onChange="select_price(this);">
          <option disabled selected value>default</option>
          <option value="0">low to high</option>
          <option value="1">high to low</option>
          <option value="1">name</option>
        </select>
      </p>
      <input type="submit" value="apply" >
    </form>
    </div>
    
   

    <div class="col-9">
      <div class="row">
          <% @products.each do |product| %>
        <div class="col-12" style="margin-top: 15px;">
          <div class="row" >
            <div class="col-3" style="padding: 10px;">
              <% if product.picture == nil %>
              <% else %>
              <div style="text-align: center;">
                <%= image_tag product.picture.image.variant(resize_to_limit: [200,200]) %>
              </div>
                
              <% end %>
            </div>
            <div class="col-6">
              <h5><%= product.productName %></h5>
              <ul>
                <li><%= product.memory %></li>
                <li><%= product.displaySize %></li>
                <li><%= product.camaras %></li>
                <li><%= product.battery %></li>
                <li><%= product.processor %></li>
              </ul>
            </div>
            <div class="col-3">
              <h5>Rs.<%= product.productPrice.to_s(:delimited) %></h5>
              <%= link_to "Add to cart", 'http://localhost:3000/cart_items?'+{product_id:product.id}.to_param,  data: { "turbo-method": :post }  %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <div>
        <%= paginate @products  %>    
      </div>
    </div>
  </div>
</div>

	

  